// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "MotionDatabase.generated.h"

UENUM(BlueprintType)
enum class EActionTag : uint8
{
	None,
	Idle,
	Run,
	Sprint,
	Turn,
	Kick,
	Tackle
};

USTRUCT(BlueprintType)
struct FMotionFeature
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector Velocity;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float FacingAngle;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FVector> JointPositions;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	EActionTag ActionTag;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int32 FrameIndex;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	UAnimSequence* SourceSequence;
};

USTRUCT(BlueprintType)
struct FMotionSearchResult
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FMotionFeature BestMatch;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float MatchScore;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float SearchTime;
};

/**
 * Motion database asset containing indexed animation frames
 * Generated by preprocessing pipeline for fast runtime queries
 */
UCLASS(BlueprintType)
class POCKETSTRIKER_API UMotionDatabase : public UDataAsset
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Motion Database")
	TArray<FMotionFeature> IndexedFrames;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Motion Database")
	TArray<UAnimSequence*> SourceAnimations;
};
